### ISSUE TITLE
CORS policy error

### ISSUE THREAD

**Issue by kinqq** [leegeunhyeok/comcigan-parser#10]
Access to fetch at 'http://xn--s39aj90b0nb2xw6xh.kr/' from origin 'http://localhost:3333' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

라는 에러가 생기네요.
해결 방법이 있을까요?

**Comment by leegeunhyeok** [comment]
개발 중이신 프론트엔드측에서 comcigan-parser 라이브러리를 사용하고 계신 것으로 보입니다.

컴시간측에서 동일 도메인이 아닌 경우 리소스 접근을 제한하고 있어(CORS), **프론트엔드에서 직접 접근할 수 없습니다.**

일반적으로, 서버(Node.js)에서 comcigan-parser 라이브러리를 통해 데이터를 수집한 후,
API 등을 이용하여 프론트엔드에게 전달하는 방법으로 해결하실 수 있습니다.

또한 해당 라이브러리는 ***Node.js 환경을 대상으로 개발***되었으니 참고 부탁드립니다.


감사합니다.
