### ISSUE TITLE
지역은 다르지만 학교명이 완전히 동일할 경우

### ISSUE THREAD

**Issue by dwsong07** [leegeunhyeok/comcigan-parser#12]
지역만 다르고 학교명이 완전히 동일하면
```Error: 검색된 학교가 많습니다. 더 자세한 학교명을 입력해주세요. 검색 결과 수: 2```
이 뜹니다.

**Comment by leegeunhyeok** [comment]
안녕하세요, 해당 이슈를 해결하기 위해 검색 로직과 학교 설정 로직을 분리하였습니다.

이제 `search` 메소드를 통해 학교를 검색하고, 결과로 전달받은 학교 리스트 내에서 원하는 학교를 선택하실 수 있습니다.
해당 기능은 `1.0.0` 버전으로 배포될 예정이며, 자세한 내용은 README의 Change Log 확인 부탁드리겠습니다.

**Comment by dwsong07** [comment]
이슈를 해결해주셔서 감사합니다.
이 대단한 물건을 어떻게 만드신겁니까.. ㄷ
잘 쓰겠습니다.
