### ISSUE TITLE
Promise pending 문제

### ISSUE THREAD

**Issue by Ethan-Seolso** [leegeunhyeok/comcigan-parser#15]
sample 폴더에 있는 sample.js 의 소스코드를 저희 학교로만 바꿔서 그대로 붙여넣고 함수 끝에대가 `return result[2][2]`만 붙였습니다.

```javascript
const parsingSchedul = async () => {
    await timetable.init();
    const schoolList = await timetable.search("늘푸른");
    const targetSchool = schoolList.find((school) => {
        return school.region === "경기" && school.name === "늘푸른중학교";
    });
    await timetable.setSchool(targetSchool.code);
    const result = await timetable.getTimetable();

    return result[2][2]
}
```

근데 저 함수에서 나온 결과값을 그대로 console.log 찍어보니 `Promise { <pending> }` 라는게 나옵니다.

저는 저기에 있는 result 라는 값을 원하는데 왜 이것이 나온것이죠?

저기에 있는 result 가 나오게 할 수는 없나요?

**Comment by Ethan-Seolso** [comment]
참고로 저는 Nodejs 환경이고 따로 api 를 만들어서 쏴주고 있는 상황으로 client 측에서 하지 않았습니다.

**Comment by myoun** [comment]
await으로 안하셨으니... 당연히 Promise가 나오는게...
``` js
parsingSchedul.then((res) => {console.log(res)})
```

**Comment by leegeunhyeok** [comment]
@Ethan-Seolso 비동기 함수는 항상 Promise 를 반환합니다.

해당 함수에서 return 한 결과 값은 resolve 된 결과로 전달되므로 then 으로 캐치하거나, await 키워드를 통해 Promise 가 완료될 때까지 대기한 후 결과를 받아야 합니다.
