### ISSUE TITLE
시정 기능에 관하여

### ISSUE THREAD

**Issue by notkimwol** [leegeunhyeok/comcigan-parser#2]
멋진 모듈을 만들어 주셔서 감사합니다.

컴시간표를 사용하는 각 학교마다 수업을 시작하는 시간이 다 다른데, 현재 버젼에서는 시간 정보를 확인할 수 있나요?

**Comment by leegeunhyeok** [comment]
안녕하세요, 늦은 피드백 대단히 죄송합니다.


데이터 확인 결과 수업시간에 대한 정보가 있는것을 확인했습니다.

![image](https://user-images.githubusercontent.com/26512984/67614863-0559c080-f7ff-11e9-8944-8f160b927b8c.png)

여러 학교를 기준으로 테스트를 진행한 후 라이브러리에서 제공할 수 있도록 추가 기능을 구현할 예정입니다. 

감사합니다 :)

**Comment by leegeunhyeok** [comment]
해당 정보 제공 기능이 `0.2.0` 버전에 구현되어 배포되었습니다.

```javascript
timetable.getClassTime()

/*
[ '1(09:10)',
  '2(10:10)',
  '3(11:10)',
  '4(12:10)',
  '5(13:50)',
  '6(14:50)',
  '7(15:50)',
  '8(16:50)' ]
*/
```

자세한 사항은 [여기](https://github.com/leegeunhyeok/comcigan-parser#method-timetablegetclasstime)를 참고해주세요
