### ISSUE TITLE
갑자기 콘솔에서 이런 오류가 발생해요

### ISSUE THREAD

**Issue by heygoodluck** [leegeunhyeok/comcigan-parser#23]
Error: 소스에서 식별 코드를 찾을 수 없습니다.
잘 작동하던 코드인데 갑자기 저러네요..

**Comment by Yellowstrawberrys** [comment]
index.js에 있는 this._baseUrl하고 this._url을 'http://comci.net:4082'와 'http://comci.net:4082/st'으로 봐꿔주면 잘 됩니다.

**Comment by Yellowstrawberrys** [comment]
최신 버전에서는 HOST를 'http://컴시간학생.kr/'으로 봐꿔주면 잘 작동 하네요

**Comment by honk7608** [comment]
저도 마찬가지 에러가 뜹니다.
같은 코드를 돌려도 몇 번은 실행이 정상적으로 되고, 몇 번은 안되네요.

**Comment by HacKoo07** [comment]
컴시간에서 수업 시간 정보는 불러오지만, 교시별 과목은 불러오지 못합니다.
