### ISSUE TITLE
파싱이 되지 않는거 같네요.

### ISSUE THREAD

**Issue by wonderlandpark** [leegeunhyeok/comcigan-parser#3]
오랜만에 다시 이 모듈을 사용하게 됬는데요 `0.2.0` 버전을 사용하고 있는데도 동일한 오류가 발생합니다.

혹시 방학이라 컴시간 시간표가 비어있나 확인도 해보았지만 그렇지 않군요

#1 과 같은 오류입니다.

**Comment by wonderlandpark** [comment]
예시 코드를 실행해보았습니다

**Comment by leegeunhyeok** [comment]
늦어서 대단히 죄송합니다.

비공식적인 방식으로 구현하기도 했지만, 컴시간 측의 주기적인 코드 변경으로 인해
항상 데이터를 정상적으로 수집하기엔 어려움이 있는 것 같습니다 😂

조금 전에 전반적으로 데이터 수집 및 파싱 로직을 보완하여 `0.3.0` 버전으로 개선하였는데, 한 번 확인 부탁드리겠습니다!
