### ISSUE TITLE
컴시간 주소 변경에 따른 파싱 이슈입니다.

### ISSUE THREAD

**Issue by kinqq** [leegeunhyeok/comcigan-parser#9]
이번 컴시간 주소 변경으로 인해 파싱이 되지 않는 문제가 발생한 것 같습니다.

[http://comci.kr/](http://comci.kr/)
에서
[http://컴시간학생.kr/](http://컴시간학생.kr/)
으로 URL이 바뀌었습니다.

수정바랍니다.

**Comment by leegeunhyeok** [comment]
안녕하세요, 전달해주신 이슈 잘 확인하였습니다!

현재 해당 문제를 비롯하여 데이터가 정상적으로 수집되지 않던 문제 등
전반적으로 코어 로직 부분을 개선하였습니다.

최종적으로 확인 후에 곧 `0.3.0` 버전으로 배포될 예정입니다.

감사합니다! 😊
